"""empty message

Revision ID: 15ce58bd6463
Revises: d83e31e2f94
Create Date: 2014-09-08 12:29:23.534006

"""

# revision identifiers, used by Alembic.
revision = '15ce58bd6463'
down_revision = 'd83e31e2f94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
