"""empty message

Revision ID: 2025fd8e4b71
Revises: 15ce58bd6463
Create Date: 2014-09-08 12:33:44.316323

"""

# revision identifiers, used by Alembic.
revision = '2025fd8e4b71'
down_revision = '15ce58bd6463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
