"""empty message

Revision ID: 277d8c8ed827
Revises: 3037bd346f30
Create Date: 2014-09-08 12:42:35.245412

"""

# revision identifiers, used by Alembic.
revision = '277d8c8ed827'
down_revision = '3037bd346f30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uni_user_code', 'password_reset', ['user', 'code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uni_user_code', 'password_reset')
    ### end Alembic commands ###
