"""empty message

Revision ID: 3037bd346f30
Revises: 2025fd8e4b71
Create Date: 2014-09-08 12:40:16.727195

"""

# revision identifiers, used by Alembic.
revision = '3037bd346f30'
down_revision = '2025fd8e4b71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
